version: '2.1'
orbs:
  semantic-release: oandacorp/semantic-release@1.1.0
workflows:
  Perform semantic-release:
    jobs:
      - semantic-release/node:
          arguments: '--dry-run'
          
          
