version: '2.1'
orbs:
  node: circleci/node@5.0.2
  baseci: microtest-health/baseci@2.0.1
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages      
      - run: npm run release

  push:
    executor: node/default
    steps:     
      - run: npm run pushToGit

  publish:
    executor: node/default
    steps:     
      - run: npm run publish
  

workflows:
  run-npm-command:
    jobs:       
      - baseci/publish-artifacts-to-github-releases  
 

      