orbs:
  maven: circleci/maven@1.3.0
version: 2.1
workflows:
  maven_test:
    jobs:
      - maven/test:
          context:
            ACOER
          filters:
            branches:
              only: test/semantic-release
          command: '-s settings.xml clean deploy'
      - maven/test:
          context:
            ACOER
          filters:
            branches:
              only: master
          command: '-s settings.xml clean deploy -P release'