version: '2.1'
orbs:
  node: circleci/node@5.0.2
  baseci: microtest-health/baseci@2.0.1
  maven-build: inclasstoday/maven-build@1.0.4
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - maven-build/maven_command:
          command: mvn -s settings.xml clean deploy 
          with_docker: false 
           
workflows:
  example-workflow:
    jobs:
      - example-job
           

      