version: 2.1
orbs:
  node: circleci/node@4.5
  semantic-release: trustedshops-public/semantic-release@2.0.0
jobs:
  release:
    executor: node/default
    steps:
      - checkout
      - node/install-packages # Install and automatically cache packages
      # Run optional required steps before releasing
      # - run: npm run build-script
      - run: npm run semantic-release

workflows:
    example-workflow:
      jobs:
        - semantic-release/with-changelog-github-config
