version: '2.1'
orbs:
  version-release: kohirens/version-release@1.1.0
workflows:
    example-workflow:
      jobs:
        - version-release/tag-and-release:
            changelogFile: ./CHANGELOG.md 
            ghToken: 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 
            branch: test/semantic-release           
          
