version: '2.1'
orbs:
  node: circleci/node@5.0.2
  baseci: microtest-health/baseci@2.0.1
  maven: circleci/maven@1.3.0
jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - node/install-packages 
workflows:
    example-workflow:
      jobs:
        - maven/parallel_test:
            command:  mvn -s settings.xml clean deploy        
 

      